name: paryatak
description: "Travel and Tourism App"

publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  firebase_storage: ^11.2.4
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2
  firebase_core: ^2.14.0
  persistent_bottom_nav_bar_v2: ^5.2.3
  fluentui_system_icons: ^1.1.232
  image_picker: ^1.0.5
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: GreatVibes
      fonts:
        - asset: fonts/GreatVibes-Regular.ttf